.Dd   June 11, 2016
.Dt   CLASSICMENU-INDICATOR 1 1
.Os   Linux

.Sh NAME
.Nm classicmenu-indicator
.Nd Classic application menu for the Unity desktop environment

.Sh SYNOPSIS
.Nm classicmenu-indicator
.Op Ar options

.Sh DESCRIPTION
ClassicMenu Indicator is a notification area applet (application indicator) for the top panel of Ubuntu’s Unity desktop environment and other environments that support the AppIndicator protocol.
It provides a simple way to get a GNOME Classic-style application menu for those who prefer this over the Unity dash menu.

.Sh OPTIONS
 Listed below are the command line options:
 
.Bl -tag -width Ds
.It Fl h , Fl -help
show this help message and exit
.It Fl -version
show program's version number and exit
.El

.Sh FILES
.Pa $HOME/.config/classicmenu-indicator

.Sh AUTHOR
Florian Diesch <devel@florian-diesch.de>
