#!/bin/sh
set -e

# Automatically added by dh_python2:
# make sure python-central files are removed before new package is installed
if [ "$1" = upgrade ] && [ -f /var/lib/pycentral/classicmenu-indicator.pkgremove ]
then
	pycentral pkgremove classicmenu-indicator
	rm -f /var/lib/pycentral/classicmenu-indicator.pkgremove
fi

# End automatically added section
